version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    network_mode: host

volumes:
  postgres-volume:
